Repository Team-Packman/Packman-Client, pull requests merged in 2022-07, with the labels that each got.

#21 feat/#19 : Add layout, header
  components/common/Header.tsx
  components/common/Layout.tsx
  pages/_app.tsx
  pages/index.tsx
  public/assets/svg/back_ic.svg
  public/assets/svg/logo.svg
  public/assets/svg/member_ic.svg
  public/assets/svg/profile_ic.svg
  public/sw.js.map
  styles/color.ts
Labels: FEAT

#26 Br/#16 패킹리스트 헤더 구현
  pages/_app.tsx
  pages/components/CategoriesWrapper.tsx
  pages/components/PackingListHeader.tsx
  pages/writing-packing-list.tsx
  public/assets/png/editButton.png
  public/assets/png/kebabButton.png
  public/sw.js.map
  styles/color.ts
Labels: FEAT

#27 프로필 뷰 구현
  components/common/Header.tsx
  pages/_app.tsx
  pages/components/common/BottomModal.tsx
  pages/components/common/Footer.tsx
  pages/components/common/Modal.tsx
  pages/components/profile/CreateProfile.tsx
  pages/components/profile/EditingProfile.tsx
  pages/components/profile/SelectProfileSection.tsx
  pages/components/profile/SettingProfile.tsx
  pages/components/selectTemplate/Template.tsx
  pages/components/selectTemplate/TemplateItem.tsx
  pages/components/selectTemplate/TemplateList.tsx
  pages/edit-profile.tsx
  pages/packing-list.tsx
  pages/profile.tsx
  pages/selectTemplate.tsx
  public/assets/svg/iClose.svg
  public/assets/svg/iToggleOff.svg
  public/assets/svg/iToggleOn.svg
  public/assets/svg/pmLogo.svg
  public/assets/svg/tempBox.svg
  public/sw.js.map
Labels: FEAT

#11 feat : 패킹 폴더 개발
  package.json
  pages/_app.tsx
  pages/_document.tsx
  pages/assets/default_profile.svg
  pages/assets/fab.svg
  pages/assets/home_init.svg
  pages/assets/kebab.svg
  pages/components/FloatActionButton.tsx
  pages/components/FolderBox.tsx
  pages/components/FolderLanding.tsx
  pages/components/FolderList.tsx
  pages/components/Swiper.tsx
  pages/components/TestLanding.tsx
  pages/components/common/BottomModal.tsx
  pages/components/layout.tsx
  pages/folder.tsx
  pages/test.tsx
  public/sw.js.map
  service/folder/index.ts
  service/folder/mockAPI.ts
  styles/color.ts
  utils/axios/folder/mock.ts
  yarn.lock
Labels: FEAT

#33 패킹리스트뷰 반영안 된 디자인, 기능 구현하기
  components/common/Header.tsx
  pages/_app.tsx
  pages/components/FolderLanding.tsx
  pages/components/common/BottomModal.tsx
  pages/components/common/Modal.tsx
  pages/components/packingList/DropBox.tsx
  pages/components/packingList/SwipeableList.tsx
  pages/components/packingList/SwipeableListItem.tsx
  pages/components/profile/ProfileLanding.tsx
  pages/components/profile/SelectProfileSection.tsx
  pages/components/profile/SettingProfile.tsx
  pages/components/selectTemplate/SelectTemplateLanding.tsx
  pages/components/selectTemplate/Template.tsx
  pages/edit-profile.tsx
  pages/index.tsx
  pages/packing-list.tsx
  pages/packing-list/[[...slug]].tsx
  pages/profile.tsx
  pages/select-template.tsx
  public/assets/svg/iCheckPink.svg
  public/assets/svg/iDelete.svg
  public/sw.js.map
  styles/color.ts
  utils/axios/ect/mock.ts
  utils/axios/packingList/alone/mock.ts
Labels: CHORE, FEAT

#36 모달 컴포넌트 수정
  pages/components/common/Modal.tsx
  public/sw.js.map
Labels: FEAT

#40 feat/#28 구글로 로그인 구현
  pages/components/PackingListHeader.tsx
  pages/login.tsx
Labels: FEAT

#38 패킹리스트 뷰에 플로팅 버튼 붙이기
  pages/components/common/Modal.tsx
  pages/components/folder/FloatActionButton.tsx
  pages/components/folder/FolderLanding.tsx
  pages/components/selectTemplate/Template.tsx
  pages/packing-list/[[...slug]].tsx
  pages/packing-list/index.tsx
  pages/select-template.tsx
  pages/select-template/[categoryName].tsx
  pages/select-template/index.tsx
  public/sw.js.map
  utils/axios/folder/mock.ts
Labels: FEAT

#31 feat/#22 함께 패킹 체크리스트 뷰
  components/common/AddTemplateButton.tsx
  components/common/FunctionSection.tsx
  components/common/Header.tsx
  components/common/Layout.tsx
  components/common/PackagesWithCategory.tsx
  components/common/Packer.tsx
  components/common/PackingCategory.tsx
  components/common/PackingItem.tsx
  components/common/SharePackingListButton.tsx
  components/together/CheckListHeader.tsx
  components/together/CheckListSubHeader.tsx
  components/together/PackerModal.tsx
  components/together/PreviewLanding.tsx
  pages/_app.tsx
  pages/components/CategoriesWrapper.tsx
  pages/components/packingList/SwipeableListItem.tsx
  pages/packing-list/[...slug].tsx
  pages/packing-list/alone/[id].tsx
  pages/packing-list/index.tsx
  pages/together/[id].tsx
  pages/writing-packing-list.tsx
  public/assets/svg/hole_ic.svg
  public/assets/svg/hole_selected_ic.svg
  public/assets/svg/home_init.svg
  public/assets/svg/kebab_ic.svg
  public/assets/svg/plus_ic.svg
  public/assets/svg/share_ic.svg
  public/sw.js.map
  service/ect/index.ts
  service/packingList/index.ts
  service/packingList/together/createAPI.ts
  service/packingList/together/index.ts
  service/packingList/together/mockAPI.ts
  service/together/createAPI.ts
  service/together/index.ts
  service/together/mockAPI.ts
  styles/color.ts
  styles/globalStyle.ts
  tsconfig.json
  utils/Draw.ts
  utils/axios/ect/mock.ts
  utils/axios/packingList/together/index.ts
  utils/axios/packingList/together/mock.ts
  utils/editHandler.ts
  utils/setCaret.ts
  utils/setScreenSize.ts
  yarn.lock
Labels: FEAT

#49 feat/#48 : 함께 패킹 리스트 서버 연결 성공(예시 코드)
  components/common/Packer.tsx
  components/together/CheckListHeader.tsx
  components/together/TogetherLanding.tsx
  pages/_app.tsx
  pages/index.tsx
  public/sw.js.map
  service/packingList/index.ts
  service/packingList/together/createAPI.ts
  service/packingList/together/index.ts
  utils/axios/packingList/together/index.ts
  utils/axios/withAuth.ts
Labels: FEAT

#53 닉네임, 프로필 등록 api 연결
  pages/components/profile/EditingProfile.tsx
  pages/components/profile/SelectProfileSection.tsx
  pages/components/profile/SettingProfile.tsx
  pages/edit-profile.tsx
  public/sw.js.map
  service/user/createAPI.ts
  service/user/index.ts
  utils/axios/user/index.ts
Labels: FEAT

#55 폴더 안 혼자 패킹 리스트들 조회 api 연결
  pages/components/common/BottomModal.tsx
  pages/components/profile/SelectProfileSection.tsx
  pages/components/selectTemplate/Template.tsx
  pages/components/selectTemplate/TemplateItem.tsx
  pages/edit-profile.tsx
  pages/packing-list/alone/[id].tsx
  pages/packing-list/together/[id].tsx
  pages/select-template/[categoryName].tsx
  service/inventory/alone/createAPI.ts
  service/inventory/alone/index.ts
  service/inventory/index.ts
  utils/inventory/alone/index.ts
Labels: FEAT

#57 feat/#50 패킹리스트 서버 연결 및 담당자 프로필 이미지 추가
  components/common/Packer.tsx
  components/common/PackingItem.tsx
  components/together/CheckListSubHeader.tsx
  components/together/PackerModal.tsx
  components/together/TogetherLanding.tsx
  public/sw.js.map
  service/packingList/together/createAPI.ts
  service/packingList/together/index.ts
  utils/Draw.ts
  utils/axios/packingList/together/index.ts
  utils/profileImages.ts
Labels: FEAT

#61 Br/#41 카카오 로그인 및 로그인 페이지 구현
  pages/_document.tsx
  pages/login.tsx
  public/assets/png/kakaoLogin.png
  public/assets/svg/kakaoLogin.svg
  public/assets/svg/loginLogo.svg
Labels: FEAT

#62 프로필 이미지 리스트 분리 및 랜딩페이지 이동
  pages/components/folder/FolderLanding.tsx
  pages/components/packingList/alone/[id].tsx
  pages/components/packingList/together/[id].tsx
  pages/components/profile/SelectProfileSection.tsx
  pages/components/profile/SettingProfile.tsx
  pages/components/selectTemplate/[categoryName].tsx
  pages/packing-list/alone/index.tsx
  pages/packing-list/together/index.tsx
  pages/select-template/index.tsx
  public/sw.js.map
Labels: FEAT

#68 템플릿 선택하기 뷰 api 연결
  pages/components/packingList/alone/AlonePackingListLanding.tsx
  pages/components/packingList/together/TogetherPackingListLanding.tsx
  pages/components/profile/SelectProfileSection.tsx
  pages/components/selectTemplate/Template.tsx
  pages/components/selectTemplate/TemplateItem.tsx
  pages/components/selectTemplate/alone/AloneSelectTemplateLanding.tsx
  pages/components/selectTemplate/together/TogetherSelectTemplateLanding.tsx
  pages/packing-list/alone/[id].tsx
  pages/packing-list/together/[id].tsx
  pages/select-template/alone.tsx
  pages/select-template/together.tsx
  public/assets/png/concert.png
  public/assets/png/jeju.png
  public/assets/png/korea_travel.png
  public/assets/png/oversea_travel.png
  public/assets/png/pet.png
  public/assets/png/random1.png
  public/assets/png/random2.png
  public/assets/png/random3.png
  public/assets/png/random4.png
  public/assets/png/toeic.png
  public/assets/svg/concert.svg
  public/assets/svg/jeju.svg
  public/assets/svg/korea_travel.svg
  public/assets/svg/oversea_travel.svg
  public/assets/svg/pet.svg
  public/assets/svg/random1.svg
  public/assets/svg/random2.svg
  public/assets/svg/random3.svg
  public/assets/svg/random4.svg
  public/assets/svg/toeic.svg
  public/sw.js.map
  service/ect/createAPI.ts
  service/ect/index.ts
  utils/axios/ect/index.ts
  utils/axios/ect/mock.ts
Labels: FEAT

#70 템플릿 선택하기 뷰에서 미리보기 뷰로 넘어갈 때 넘기는 id가 이상한 문제 수정
  pages/components/packingList/together/TogetherPackingListLanding.tsx
  pages/components/selectTemplate/Template.tsx
  pages/components/selectTemplate/TemplateItem.tsx
  pages/edit-profile.tsx
  public/sw.js.map
Labels: CHORE

#72 feat/#66 : 템플릿 미리보기 서버 연결
  components/alone/AloneLanding.tsx
  components/common/AddTemplateButton.tsx
  components/common/Header.tsx
  components/common/Layout.tsx
  components/common/PackingCategory.tsx
  components/common/PackingItem.tsx
  components/common/SharePackingListButton.tsx
  components/preview/PreviewLanding.tsx
  components/together/CheckListHeader.tsx
  components/together/TogetherLanding.tsx
  public/sw.js.map
  service/ect/createAPI.ts
  service/ect/index.ts
  utils/axios/ect/index.ts
Labels: FEAT

#73 함께 패킹 리스트 삭제 api 연결
  pages/components/packingList/together/TogetherPackingListLanding.tsx
  public/sw.js.map
  service/inventory/together/createAPI.ts
  service/inventory/together/index.ts
  utils/inventory/together/index.ts
Labels: FEAT

#77 feat/#75 kakao login 연결
  components/together/PackerModal.tsx
  pages/login.tsx
  public/sw.js.map
  service/auth/createAPI.ts
  service/auth/index.ts
  service/index.ts
  utils/axios/auth/index.ts
Labels: FEAT

#79 feat/#78 : 함께 패킹 리스트 > 나의 패킹 구현
  components/common/PackingCategory.tsx
  components/common/PackingItem.tsx
  components/together/TogetherLanding.tsx
  pages/login.tsx
  public/sw.js.map
  service/packingList/alone/createAPI.ts
  service/packingList/alone/index.ts
  service/packingList/index.ts
  utils/axios/packingList/alone/index.ts
Labels: FEAT

#76 혼자 패킹 리스트 삭제 api 연결
  pages/components/packingList/DropBox.tsx
  pages/components/packingList/SwipeableList.tsx
  pages/components/packingList/alone/AlonePackingListLanding.tsx
  pages/components/packingList/together/TogetherPackingListLanding.tsx
  pages/components/profile/SelectProfileSection.tsx
  pages/components/profile/SettingProfile.tsx
  pages/components/selectTemplate/Template.tsx
  pages/components/selectTemplate/alone/AloneSelectTemplateLanding.tsx
  public/sw.js.map
  service/inventory/alone/createAPI.ts
  service/inventory/alone/index.ts
  service/inventory/together/createAPI.ts
  service/user/createAPI.ts
  utils/axios/folder/index.ts
  utils/inventory/alone/index.ts
Labels: FEAT

#81 Br/#64 feat
  pages/components/common/ModalForInvitation.tsx
  pages/components/common/ModalForInvited.tsx
  pages/components/common/ModalForShare.tsx
  pages/components/common/ModalForShared.tsx
  pages/modal-test.tsx
  public/assets/png/ButtonX.png
  public/assets/png/forShare.png
  public/sw.js.map
Labels: FEAT

#84 feat/#78 : 혼자 패킹 리스트 api 연결, list-intro 프롭 수정
  components/alone/AloneLanding.tsx
  components/common/PackingItem.tsx
  components/together/TogetherLanding.tsx
  pages/components/common/BottomModal.tsx
  pages/components/listIntro/ListIntroLanding.tsx
  public/sw.js.map
Labels: FEAT

#86 Br/#85 버그 잡기
  components/common/BottomModal.tsx
  components/common/Footer.tsx
  components/common/Header.tsx
  components/common/Modal.tsx
  components/packingList/SwipeableList.tsx
  components/packingList/SwipeableListItem.tsx
  components/packingList/alone/AlonePackingListLanding.tsx
  components/packingList/together/TogetherPackingListLanding.tsx
  components/profile/CreateProfile.tsx
  components/profile/SelectProfileSection.tsx
  components/profile/SettingProfile.tsx
  components/selectTemplate/Template.tsx
  components/selectTemplate/TemplateItem.tsx
  components/selectTemplate/alone/AloneSelectTemplateLanding.tsx
  components/selectTemplate/together/TogetherSelectTemplateLanding.tsx
  pages/_app.tsx
  pages/_document.tsx
  pages/edit-profile.tsx
  pages/login.tsx
  styles/font.ts
  styles/globalStyle.ts
  type/globalState.ts
Labels: CHORE

#90 Br/#87
  components/folder/FloatActionButton.tsx
  components/packingList/SwipeableList.tsx
  components/packingList/alone/AlonePackingListLanding.tsx
  components/packingList/together/TogetherPackingListLanding.tsx
  components/profile/SettingProfile.tsx
  components/selectTemplate/alone/AloneSelectTemplateLanding.tsx
  components/selectTemplate/together/TogetherSelectTemplateLanding.tsx
  package.json
  public/assets/index.ts
  public/assets/lottie/loading.json
  utils/AsyncBoundary.tsx
  yarn.lock
Labels: FEAT

#92 chore/#91 : QA 반영
  components/packingList/SwipeableList.tsx
  components/packingList/SwipeableListItem.tsx
  components/packingList/alone/AlonePackingListLanding.tsx
  components/packingList/together/TogetherPackingListLanding.tsx
  public/assets/lottie/loading.json
Labels: CHORE

#93 Br/#89 feat: 에러 시 띄울 화면 구현
  components/common/Error.tsx
  pages/modal-test.tsx
  public/assets/png/ErrorImage.png
  utils/AsyncBoundary.tsx
Labels: FEAT

#97 Fix/#96 : 최근 생성 리스트 에러 수정
  components/folder/FolderLanding.tsx
Labels: FIX

#95 feat/#94 : Change root, delete index.tsx
  next.config.js
  pages/index.tsx
Labels: FEAT

#99 feat/#98 : 패킹리스트 바텀 모달 기능, 애니메이션 추가
  components/common/TogetherLandingBottom.tsx
  components/together/TogetherLanding.tsx
Labels: FEAT

#101 Fix/#100 : 혼자패킹리스트 오류 수정, 기능 추가
  components/alone/AloneLanding.tsx
  components/common/PackingListBottomModal.tsx
  components/together/TogetherLanding.tsx
Labels: FEAT

#103 chore/#102 : redirect 환경 변수 분리
  .gitignore
  pages/login.tsx
Labels: CHORE

#106 fix/#105 : 템플릿 미리보기 오류 수정
  components/common/SharePackingListButton.tsx
  components/preview/PreviewLanding.tsx
  package.json
Labels: FIX
