Repository Team-Packman/Packman-Client, pull requests merged in 2022-08, with the labels that each got.

#109 fix/#108 프로필 성공시 라우팅 경로 수정, 이메일 삽입
  components/profile/SelectProfileSection.tsx
Labels: FIX

#111 feat/#110 : 카카오 로그인 리뉴얼
  pages/_document.tsx
  pages/login.tsx
Labels: FEAT

#114 Br/#104 패킹리스트 qa 반영
  components/folder/FloatActionButton.tsx
  components/packingList/SwipeableList.tsx
  components/packingList/SwipeableListItem.tsx
  components/packingList/alone/AlonePackingListLanding.tsx
  components/packingList/together/TogetherPackingListLanding.tsx
  components/profile/SettingProfile.tsx
Labels: BUG, CHORE

#125 Br/#124 image, manifest meta 수정
  package.json
  pages/_document.tsx
  public/assets/pwa/apple-icon-180.png
  public/assets/pwa/apple-splash-1125-2436.jpg
  public/assets/pwa/apple-splash-1136-640.jpg
  public/assets/pwa/apple-splash-1170-2532.jpg
  public/assets/pwa/apple-splash-1242-2208.jpg
  public/assets/pwa/apple-splash-1242-2688.jpg
  public/assets/pwa/apple-splash-1284-2778.jpg
  public/assets/pwa/apple-splash-1334-750.jpg
  public/assets/pwa/apple-splash-1536-2048.jpg
  public/assets/pwa/apple-splash-1620-2160.jpg
  public/assets/pwa/apple-splash-1668-2224.jpg
  public/assets/pwa/apple-splash-1668-2388.jpg
  public/assets/pwa/apple-splash-1792-828.jpg
  public/assets/pwa/apple-splash-2048-1536.jpg
  public/assets/pwa/apple-splash-2048-2732.jpg
  public/assets/pwa/apple-splash-2160-1620.jpg
  public/assets/pwa/apple-splash-2208-1242.jpg
  public/assets/pwa/apple-splash-2224-1668.jpg
  public/assets/pwa/apple-splash-2388-1668.jpg
  public/assets/pwa/apple-splash-2436-1125.jpg
  public/assets/pwa/apple-splash-2532-1170.jpg
  public/assets/pwa/apple-splash-2688-1242.jpg
  public/assets/pwa/apple-splash-2732-2048.jpg
  public/assets/pwa/apple-splash-2778-1284.jpg
  public/assets/pwa/apple-splash-640-1136.jpg
  public/assets/pwa/apple-splash-750-1334.jpg
  public/assets/pwa/apple-splash-828-1792.jpg
  public/assets/pwa/manifest-icon-192.maskable.png
  public/assets/pwa/manifest-icon-512.maskable.png
  public/manifest.json
Labels: FEAT

#123 Br/#113 모달 등록
  components/alone/AloneLanding.tsx
  components/common/ModalForAddToTemplate.tsx
  components/common/ModalForInvitation.tsx
  components/common/ModalForInvited.tsx
  components/common/ModalForShare.tsx
  components/common/SharePackingListButton.tsx
  components/together/TogetherLanding.tsx
  pages/alone/[id].tsx
  pages/alone/invited/[id].tsx
  pages/login.tsx
  pages/preview/index.tsx
  pages/together/invited/[id].tsx
  utils/AsyncBoundary.tsx
Labels: FEAT

#127 feat/#126 : manifest.json shorcuts 추가
  .gitignore
  public/manifest.json
  public/sw.js
Labels: FEAT

#129 Br/#128 : 업데이트 알림 모달 추가(테스트)
  .gitignore
  components/common/UpdateNotification.tsx
  pages/_app.tsx
  pages/fallback.tsx
  public/sw.js
Labels: FEAT

#131 Br/#130 : ios/and 앱 설치 알림 추가
  components/common/InstallGuide.tsx
  pages/_app.tsx
  utils/hooks/useInstallGuide.tsx
Labels: FEAT

#116 Br/#115 폴더뷰 디자인 수정
  components/common/BottomModal.tsx
  components/folder/FloatActionButton.tsx
  components/folder/FolderBox.tsx
  pages/assets/fab.svg
  pages/assets/fab_rotate.svg
  pages/assets/kebab.svg
Labels: FIX

#121 Br/#119 프로필 수정 뷰 스크롤 버그 수정 및 로그아웃 기능 추가
  components/packingList/alone/AlonePackingListLanding.tsx
  components/packingList/together/TogetherPackingListLanding.tsx
  components/profile/SettingProfile.tsx
  pages/edit-profile.tsx
  pages/login.tsx
  utils/recoil/atom/atom.ts
  utils/recoil/atom/index.ts
Labels: CHORE, FEAT

#135 Br/#133 프로필 수정 뷰 버그 수정
  components/common/Modal.tsx
  components/profile/EditingProfile.tsx
  components/profile/SelectProfileSection.tsx
  components/profile/SettingProfile.tsx
  pages/edit-profile.tsx
Labels: CHORE

#136 Br/#134 업데이트 알림 위치 수정 / 안드에서 설치버튼 작동하도록 수정
  components/common/InstallGuide.tsx
  utils/hooks/useInstallGuide.tsx
Labels: FEAT, FIX

#138 fix/#137 : os 구분 로직 수정
  components/common/InstallGuide.tsx
  pages/_app.tsx
  public/sw.js
  utils/hooks/useInstallGuide.tsx
Labels: FIX

#144 Br/#139 템플릿 선택하기 뷰 템플릿 디자인 수정
  components/packingList/SwipeableListItem.tsx
  components/selectTemplate/Template.tsx
  components/selectTemplate/TemplateList.tsx
  components/selectTemplate/alone/AloneSelectTemplateLanding.tsx
  components/selectTemplate/together/TogetherSelectTemplateLanding.tsx
Labels: CHORE

#150 chore/#149 : vconsole 삭제, 에러메시지 출력
  components/common/Error.tsx
  package.json
  yarn.lock
Labels: CHORE, FIX

#152 chore/#151 : vconsole 잔해 삭제
  components/packingList/alone/AlonePackingListLanding.tsx
  components/packingList/together/TogetherPackingListLanding.tsx
Labels: FIX

#154 chore/#153 : 리스트 목록 뷰 아이템 클릭 시 라우팅 방법 변경
  components/packingList/SwipeableListItem.tsx
  components/packingList/alone/AlonePackingListLanding.tsx
  components/packingList/together/TogetherPackingListLanding.tsx
Labels: CHORE, FEAT

#157 Br/#156 리스트 목록 뷰 Safari 애니메이션 버벅거림 수정
  components/packingList/SwipeableListItem.tsx
Labels: FEAT

#143 Br/#142 : 로그인 세션 만료, 권한 처리 로직 추가
  utils/axios/withAuth.tsx
Labels: FEAT

#140 Fix/#132 폴더뷰 에러 수정 2
  components/folder/FloatActionButton.tsx
  components/folder/FolderBox.tsx
  components/folder/FolderInitial.tsx
  components/folder/FolderLanding.tsx
  components/folder/FolderList.tsx
  public/assets/svg/fab.svg
  public/assets/svg/fab_rotate.svg
  public/assets/svg/home_init_alone.svg
Labels: FIX

#161 feat/#160 : 함께패킹리스트 디자인 깨짐 수정
  components/common/PackagesWithCategory.tsx
  components/together/CheckListSubHeader.tsx
  components/together/TogetherLanding.tsx
Labels: FEAT

#162 Br/#112 멤버 관리 뷰 메인화면 구현
  pages/member-manage.tsx
  pages/modal-test.tsx
  public/assets/png/crown.png
  public/assets/svg/loginLogo.svg
Labels: CSS, FEAT

#166 Br/#160 함께패킹리스트 디자인 이슈 리오픈
  components/common/PackagesWithCategory.tsx
  components/together/CheckListSubHeader.tsx
Labels: FEAT

#167 Br/#160 : 패킹 아이템 width 조정
  components/common/PackagesWithCategory.tsx
  components/together/TogetherLanding.tsx
Labels: FEAT

#165 Br/#158 리스트 애니메이션 및 프로필 수정 뷰 디자인 수정
  components/packingList/SwipeableListItem.tsx
  components/profile/SelectProfileSection.tsx
  components/selectTemplate/TemplateList.tsx
  pages/edit-profile.tsx
Labels: CHORE

#168 Br/#160 : 영역 확인 테스트
  components/common/PackagesWithCategory.tsx
  components/together/TogetherLanding.tsx
Labels: FEAT

#169 Br/#160 : 전역 스타일 -webkit-box-sizing 추가
  styles/globalStyle.ts
Labels: FEAT

#170 feat/#160 : 아이템 추가 버튼을 svg로 변경
  components/common/PackagesWithCategory.tsx
  components/together/TogetherLanding.tsx
  public/assets/svg/add_item_ic.svg
Labels: FEAT

#172 chore/#171 : 리스트목록뷰 아이템 트랜지션 버벅거림 이슈 해결하기
  components/packingList/SwipeableListItem.tsx
Labels: CHORE

#174 Br/#160 패킹리스트 아이템 추가 버튼 디자인 수정
  components/common/PackagesWithCategory.tsx
  components/common/PackingItem.tsx
  components/together/CheckListSubHeader.tsx
  components/together/TogetherLanding.tsx
Labels: FEAT, STYLE

#175 Br/#155 QA 반영 및 리팩토링
  components/common/Error.tsx
  components/common/Modal.tsx
  components/packingList/DropBox.tsx
  components/packingList/SwipeableListItem.tsx
  components/packingList/alone/AlonePackingListLanding.tsx
  components/packingList/together/TogetherPackingListLanding.tsx
  components/profile/SelectProfileSection.tsx
  components/selectTemplate/Template.tsx
  components/selectTemplate/TemplateItem.tsx
  components/selectTemplate/TemplateList.tsx
  components/selectTemplate/alone/AloneSelectTemplateLanding.tsx
  components/selectTemplate/together/TogetherSelectTemplateLanding.tsx
  styles/globalStyle.ts
  utils/AsyncBoundary.tsx
Labels: CHORE

#178 Br/#176 패킹이 이미지 파일 추가 / 스낵바 오류 수정
  components/common/InstallGuide.tsx
  pages/_document.tsx
  public/assets/png/character1.png
  public/assets/png/character2.png
  public/assets/png/character3.png
  public/assets/png/character4.png
  public/assets/png/character5.png
  public/assets/png/character6.png
  public/assets/png/landing-bg.png
  service/ect/createAPI.tsx
  utils/hooks/useInstallGuide.tsx
Labels: FEAT, FIX, STYLE

#179 Br/#177 프로필 뷰 api 수정
  components/profile/SelectProfileSection.tsx
  components/profile/SettingProfile.tsx
  pages/login.tsx
  service/user/createAPI.tsx
  service/user/index.ts
  utils/recoil/atom/atom.ts
Labels: FEAT

#183 Br/#180 /auth/kakao (api) 변경사항 반영
  service/auth/index.ts
  utils/recoil/atom/atom.ts
  utils/recoil/atom/index.ts
Labels: FEAT

#191 Br/#180 1주차 api 변경사항 반영 / api context 구조 변경
  components/alone/AloneLanding.tsx
  components/alone/listIntro/ListIntroLanding.tsx
  components/common/ModalForInvited.tsx
  components/common/Packer.tsx
  components/profile/SelectProfileSection.tsx
  components/profile/SettingProfile.tsx
  components/together/PackerModal.tsx
  components/together/TogetherLanding.tsx
  pages/_app.tsx
  pages/login.tsx
  service/auth/createAPI.tsx
  service/auth/index.ts
  service/index.tsx
  service/packingList/alone/index.ts
  service/packingList/together/createAPI.tsx
  service/packingList/together/index.ts
  service/user/index.ts
  utils/axios/auth/index.ts
  utils/axios/packingList/together/index.ts
  utils/axios/packingList/together/mock.ts
  utils/axios/withAuth.tsx
  utils/context/apiContext.tsx
  utils/hooks/useAPI.tsx
  utils/recoil/atom/atom.ts
  utils/recoil/atom/index.ts
Labels: FEAT

#192 Br/#190 폴더 안 패킹 리스트 조회 api 수정 사항 변경
  components/packingList/DropBox.tsx
  components/packingList/SwipeableList.tsx
  components/packingList/SwipeableListItem.tsx
  components/packingList/alone/AlonePackingListLanding.tsx
  components/packingList/together/TogetherPackingListLanding.tsx
  service/inventory/alone/index.ts
  service/inventory/together/index.ts
  utils/inventory/alone/index.ts
  utils/inventory/together/index.ts
Labels: CHORE

#194 Br/#193 mock data 타입 수정
  components/profile/SelectProfileSection.tsx
  service/ect/index.ts
  service/packingList/alone/index.ts
  service/user/index.ts
  utils/axios/ect/mock.ts
  utils/axios/packingList/alone/mock.ts
  utils/axios/user/mock.ts
Labels: CHORE

#195 Br/#180 APIContext 무한루프 에러 수정(전달)
  pages/_app.tsx
  service/auth/createAPI.tsx
  service/index.tsx
  utils/axios/axios.ts
  utils/axios/withAuth.tsx
  utils/context/apiContext.tsx
  utils/hooks/queries/auth/auth.ts
Labels: FEAT, FIX

#184 [WiP]fix/#181 : 폴더뷰 api 수정
  components/alone/listIntro/ListIntroLanding.tsx
  components/folder/FolderBox.tsx
  components/folder/FolderLanding.tsx
  components/folder/FolderList.tsx
  service/folder/index.ts
  service/packingList/alone/index.ts
  service/packingList/together/index.ts
  utils/axios/folder/mock.ts
Labels: FIX

#189 fix/#187 : 첫번째 폴더 생성 안되는 문제 수정
  components/Swiper.tsx
  components/folder/FolderLanding.tsx
  components/folder/FolderList.tsx
Labels: FIX

#197 feat/#180 : token refresh 기능 추가
  service/auth/createAPI.tsx
  service/auth/index.ts
  utils/axios/auth/index.ts
  utils/axios/withAuth.tsx
  utils/hooks/queries/auth/auth.ts
Labels: FEAT

#199 Br/#180 ver.1 API 변경사항 반영
  components/alone/listIntro/ListIntroLanding.tsx
  components/common/ModalForInvitation.tsx
  components/common/ModalForInvited.tsx
  components/selectTemplate/alone/AloneSelectTemplateLanding.tsx
  components/selectTemplate/together/TogetherSelectTemplateLanding.tsx
  components/together/PackerModal.tsx
  pages/login.tsx
  pages/together/invited/[id].tsx
  service/packingList/together/createAPI.tsx
  service/packingList/together/index.ts
  utils/axios/packingList/together/index.ts
  utils/recoil/atom/atom.ts
  utils/recoil/atom/index.ts
Labels: FEAT

#200 hotfix/#180 : 테스트를 위해 에러 주석
  components/alone/listIntro/ListIntroLanding.tsx
Labels: HOTFIX

#202 hotfix/#201 : 타입 동기화 및 기타 에러 주석
  components/folder/FolderLanding.tsx
  components/profile/SettingProfile.tsx
  components/selectTemplate/Template.tsx
  components/selectTemplate/TemplateItem.tsx
  components/selectTemplate/alone/AloneSelectTemplateLanding.tsx
  components/selectTemplate/together/TogetherSelectTemplateLanding.tsx
  pages/edit-profile.tsx
  utils/axios/packingList/alone/mock.ts
Labels: HOTFIX

#186 fix/#173 : 리스트 작성하기 뷰 수정 및 기능 추가
  components/alone/listIntro/ListIntroLanding.tsx
  components/packingList/together/TogetherPackingListLanding.tsx
  components/selectTemplate/alone/AloneSelectTemplateLanding.tsx
  components/selectTemplate/together/TogetherSelectTemplateLanding.tsx
  service/packingList/together/index.ts
Labels: FEAT, FIX

#206 Br/#203 api 2주차 변경사항 반영
  components/alone/AloneLanding.tsx
  components/together/TogetherLanding.tsx
  pages/login.tsx
  service/packingList/alone/createAPI.tsx
  service/packingList/alone/index.ts
  service/packingList/together/createAPI.tsx
  utils/axios/packingList/alone/index.ts
  utils/axios/packingList/together/index.ts
Labels: FEAT

#208 feat/#204 : 2주차 api 수정 - 1
  components/alone/listIntro/ListIntroLanding.tsx
  service/packingList/together/index.ts
  utils/axios/packingList/alone/index.ts
  utils/axios/packingList/together/index.ts
Labels: FIX

#205 Br/#198 3주차 api 변경사항 반영
  components/folder/FolderLanding.tsx
  components/packingList/alone/AlonePackingListLanding.tsx
  components/packingList/together/TogetherPackingListLanding.tsx
  components/profile/SettingProfile.tsx
  package.json
  pages/edit-profile.tsx
  pages/login.tsx
  service/inventory/alone/createAPI.tsx
  service/inventory/together/createAPI.tsx
  service/user/createAPI.tsx
  utils/axios/user/index.ts
  yarn.lock
Labels: CHORE, FIX

#214 fix/#213 : 나만의 템플릿 추가 request body 수정
  .gitignore
  components/alone/AloneLanding.tsx
  components/together/TogetherLanding.tsx
Labels: FIX

#212 Br/#211 AsyncBoundary 리팩토링
  components/alone/AloneLanding.tsx
  components/common/Loading.tsx
  components/together/TogetherLanding.tsx
  utils/AsyncBoundary.tsx
Labels: REFACTOR

#218 Br/#216 템플릿 생성 플로우 추가
  components/alone/listIntro/ListIntroLanding.tsx
  components/common/PackagesWithCategory.tsx
  components/preview/PreviewLanding.tsx
  components/selectTemplate/alone/AloneSelectTemplateLanding.tsx
  components/selectTemplate/together/TogetherSelectTemplateLanding.tsx
  service/ect/createAPI.tsx
  service/ect/index.ts
  utils/axios/ect/index.ts
  utils/axios/ect/mock.ts
Labels: FEAT

#220 Br/#219 custom router 추가
  components/common/Header.tsx
  components/common/Layout.tsx
  pages/alone/index.tsx
  pages/together/index.tsx
  utils/hooks/useHeaderRouter.ts
Labels: FEAT

#224 Br/#221 리스트 목록 뷰 스와이프 버그 수정
  components/folder/FolderLanding.tsx
  components/packingList/DropBox.tsx
  components/packingList/SwipeableListItem.tsx
  components/packingList/alone/AlonePackingListLanding.tsx
  components/packingList/together/TogetherPackingListLanding.tsx
  components/profile/SettingProfile.tsx
  pages/edit-profile.tsx
  pages/packing-list/alone.tsx
  pages/packing-list/together.tsx
  pages/packing-list/together/[id].tsx
  utils/hooks/useHeaderRouter.ts
Labels: CHORE

#223 Fix/#222 3주차 API 수정
  components/alone/listIntro/ListIntroLanding.tsx
  components/common/BottomModal.tsx
  components/folder/FolderLanding.tsx
  service/folder/index.ts
Labels: FEAT

#227 feat/#226 : 함께 패킹리스트 초대 로직 수정
  components/common/ModalForInvitation.tsx
  pages/together/invited/[id].tsx
  service/packingList/together/index.ts
  utils/axios/folder/mock.ts
Labels: FEAT
