Repository Team-Packman/Packman-Client, pull requests merged in 2022-10, with the labels that each got.

#370 Br/#369 : 최종 수정사항 반영
  components/login/LoginLanding.tsx
  components/profile/SettingProfile.tsx
Labels: FEAT

#371 Br/#368 추가 요구사항 반영
  components/PackingListHeader.tsx
  components/common/CustomImage.tsx
  components/profile/ProfileLanding.tsx
  components/profile/SelectProfileSection.tsx
  components/together/CheckListSubHeader.tsx
  components/together/TogetherLanding.tsx
  pages/alone/index.tsx
  pages/together/invited/index.tsx
  service/packingList/common/createAPI.ts
  service/packingList/common/index.ts
  service/user/index.ts
  utils/axios/packingList/common/index.ts
Labels: FEAT, FIX

#372 Br/#368 추가 요구사항 반영
  pages/500.tsx
  pages/together/invited/index.tsx
  public/sw.js
  utils/AsyncBoundary.tsx
Labels: FEAT, TEST

#374 Fix/#373 폴더 에러 수정
  components/folder/FolderBox.tsx
  components/folder/FolderLanding.tsx
Labels: FIX

#376 Br/#375 : 앗차차 로직 수정 / 초대장 도메인 수정
  components/alone/listIntro/ListIntroLanding.tsx
  components/common/Error.tsx
  components/common/ModalForShare.tsx
  public/sw.js
  utils/AsyncBoundary.tsx
Labels: FIX

#381 프로필 등록 POST 수정
  components/profile/SelectProfileSection.tsx
  utils/recoil/atom/atom.ts
  utils/recoil/atom/index.ts
Labels: FIX
