Repository Team-Packman/Packman-Client, pull requests merged in 2023-03, with the labels that each got.

#400 함께 패킹 링크 공유시, 패킹리스트명 노출
  components/HeadMeta.tsx
  components/alone/AloneLanding.tsx
  components/together/TogetherLanding.tsx
  components/together/invited/InvitedLanding.tsx
  package.json
  pages/_app.tsx
  pages/_document.tsx
  pages/together/invited/index.tsx
  yarn.lock
Labels: FEAT

#401 PK-23 [멤버 관리] 멤버 편집 중 멤버 갱신 오류 수정
  components/memberManage/ManagingMemberLanding.tsx
Labels: FEAT, FIX

#402 fix/PK-18: app에서 show 상태에 따라 ealry return을 시키는 구문 제거 테스트
  pages/_app.tsx
Labels: FIX

#403 feat/PK-18: react-cookie, getInitialProps로 메타 태그 설정
  components/together/TogetherLanding.tsx
  pages/_app.tsx
  pages/together/index.tsx
  service/packingList/together/createAPI.tsx
  utils/hooks/auth/index.ts
Labels: FEAT, FIX

#399 PK-17: Dropdown 컴포넌트 통합 및 폴더 안 패킹리스트 리팩토링
  .eslintrc.json
  components/common/Dropdown.tsx
  components/packingList/CaptionSection.tsx
  components/packingList/DropBox.tsx
  components/packingList/FolderDropBox.tsx
  components/packingList/PackingListLanding.tsx
  components/packingList/SwipeableListItem.tsx
  pages/_app.tsx
  styles/globalStyle.ts
  utils/axios/index.tsx
  utils/axios/user/index.ts
  utils/axios/user/mock.ts
  utils/hooks/queries/inventory/index.ts
Labels: FEAT, REFACTOR

#396 PK-20 폴더 / 리스트 생성하기 관련 API 수정
  components/alone/listIntro/ListIntroLanding.tsx
  components/folder/FolderLanding.tsx
  service/packingList/alone/index.ts
  service/packingList/together/index.ts
Labels: FEAT

#392 PK-12 - 최근생성리스트, 멤버관리 배너 통합
  components/Swiper.tsx
  components/common/Card.tsx
  components/common/Chip.tsx
  components/folder/FolderLanding.tsx
  components/folder/FolderList.tsx
  components/memberManage/ManagingMemberLanding.tsx
  components/packingList/PackingListLanding.tsx
  components/packingList/SwipeableList.tsx
  components/packingList/SwipeableListItem.tsx
  utils/Utility.tsx
Labels: REFACTOR
