Repository Team-Packman/Packman-Client, pull requests merged in 2023-04, with the labels that each got.

#408 PM-111 [혼자 패킹 리스트] 여러 리스트 삭제 체크를 하고 화면을 내리면 삭제 체크가 사라진다
  components/packingList/PackingListLanding.tsx
Labels: FIX

#410 [QA] 카카오로그인 버튼 하단의 [이용약관]과 [개인정보 처리 방침] 링크에 정상적으로 접속 안됨 이슈 해결
  components/login/LoginLanding.tsx
  utils/constant/index.ts
Labels: FIX

#409 PK-25 [QA]리스트 작성하기 뷰(리스트 생성) 안드로이드 디바이스에서 버튼 움직이는 이슈
  components/alone/listIntro/ListIntroLanding.tsx
  utils/Utility.tsx
  utils/hooks/useInstallGuide.tsx
Labels: FIX

#414 feat/PK-18: invited 함께, 혼자 SSR 코드 수정
  components/together/invited/InvitedLanding.tsx
  pages/alone/invited/index.tsx
  pages/together/invited/index.tsx
Labels: FIX

#411 [PM-120] 함께패킹리스트 멤버 연속 삭제가 안되는 버그 수정
  components/memberManage/ManagingMemberLanding.tsx
  utils/hooks/common/useQueryString.tsx
Labels: FEAT, FIX

#416 [PM-120] 최초 localMembers가 없는 경우에 대한 에러 수정
  components/memberManage/ManagingMemberLanding.tsx
Labels: FIX

#419 [PM-70] SSR 오류 수정
  components/alone/AloneLanding.tsx
  components/common/Header.tsx
  pages/_app.tsx
  pages/alone/index.tsx
  pages/alone/invited/index.tsx
  pages/folder/index.tsx
  pages/together/index.tsx
  pages/together/invited/index.tsx
  utils/hooks/queries/auth/auth.ts
  utils/recoil/atom/atom.ts
Labels: FEAT, FIX, REFACTOR

#420 [PM-70] next-bundle-analyzer 추가
  next.config.js
  package.json
  public/sw.js
  yarn.lock
Labels: CHORE

#421 [PM-70] 불필요한 SSR 제거
  pages/alone/index.tsx
  pages/together/index.tsx
Labels: REFACTOR

#415 [PK-31] 폴더 안 패킹리스트 '아직 n개의 짐이 남았어요' 텍스트 미표시
  components/common/BottomModal.tsx
  components/common/Card.tsx
  components/common/Chip.tsx
  components/common/Error.tsx
  components/common/PackingListBottomModal.tsx
  components/folder/FloatActionButton.tsx
  components/memberManage/ManagingMemberLanding.tsx
  components/packingList/SwipeableListItem.tsx
Labels: FIX

#422 proxy 설정 및 Safari 상단바 색상 meta tag 추가
  components/folder/FloatActionButton.tsx
  components/login/LoginLanding.tsx
  next.config.js
  package.json
  pages/_document.tsx
  public/sw.js
  utils/constant/index.ts
  yarn.lock
Labels: FEAT

#423 fix/PK-36:리스트 작성하기 빈 폴더 생성 이슈 수정
  components/alone/listIntro/ListIntroLanding.tsx
Labels: FIX

#425 [PK-35] 디자인 QA 반영
  components/login/LoginLanding.tsx
  components/profile/SettingProfile.tsx
Labels: CSS

#426 함께패킹리스트 나만의 템플릿 추가하기(업데이트) 문구 수정 및 모달 띄우기
  components/alone/AloneLanding.tsx
  components/common/ModalForInvitation.tsx
  components/together/TogetherLanding.tsx
  next.config.js
  service/packingList/together/index.ts
  utils/axios/auth/index.ts
  utils/axios/index.tsx
  utils/hooks/queries/inventory/index.ts
Labels: FIX
